'------------------------------------------------------------------------------
' <autogenerated>
'     This class was generated by a tool.
'     Runtime Version: 2000.14.1812.10
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Imports System.Xml.Serialization
Imports System.Web.Services.Protocols
Imports System.Web.Services

Namespace VistaSiteMgr
    Public Class Activity
        Inherits System.Web.Services.Protocols.SoapClientProtocol
        
        Public Sub New()
            MyBase.New
            Me.Path = "http://localhost/POILib/Activity.asmx"
        End Sub
        
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/BrowseByLocationID"), System.Web.Services.Protocols.SoapParameterAttribute("startDate", ElementName:="StartDate"), System.Web.Services.Protocols.SoapParameterAttribute("endDate", ElementName:="EndDate"), System.Web.Services.Protocols.SoapParameterAttribute("locationID", ElementName:="LocationID"), System.Web.Services.Protocols.SoapParameterAttribute("categories", ElementName:="Categories")> BrowseByLocationID(ByVal startDate As String, ByVal endDate As String, ByVal locationID As Long, ByVal categories As String) As System.Data.DataSet
            Dim results As Object() = Me.Invoke("BrowseByLocationID", New Object() {startDate, endDate, locationID, categories})
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function BeginBrowseByLocationID(ByVal startDate As String, ByVal endDate As String, ByVal locationID As Long, ByVal categories As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("BrowseByLocationID", New Object() {startDate, endDate, locationID, categories}, callback, asyncState)
        End Function
        Public Function EndBrowseByLocationID(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/BrowseByLocation"), System.Web.Services.Protocols.SoapParameterAttribute("startDate", ElementName:="StartDate"), System.Web.Services.Protocols.SoapParameterAttribute("endDate", ElementName:="EndDate"), System.Web.Services.Protocols.SoapParameterAttribute("city", ElementName:="City"), System.Web.Services.Protocols.SoapParameterAttribute("region", ElementName:="Region"), System.Web.Services.Protocols.SoapParameterAttribute("stateAbbr", ElementName:="StateAbbr"), System.Web.Services.Protocols.SoapParameterAttribute("countryAbbr", ElementName:="CountryAbbr"), System.Web.Services.Protocols.SoapParameterAttribute("continent", ElementName:="Continent"), System.Web.Services.Protocols.SoapParameterAttribute("categories", ElementName:="Categories")> BrowseByLocation(ByVal startDate As String, ByVal endDate As String, ByVal city As String, ByVal region As String, ByVal stateAbbr As String, ByVal countryAbbr As String, ByVal continent As String, ByVal categories As String) As System.Data.DataSet
            Dim results As Object() = Me.Invoke("BrowseByLocation", New Object() {startDate, endDate, city, region, stateAbbr, countryAbbr, continent, categories})
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function BeginBrowseByLocation(ByVal startDate As String, ByVal endDate As String, ByVal city As String, ByVal region As String, ByVal stateAbbr As String, ByVal countryAbbr As String, ByVal continent As String, ByVal categories As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("BrowseByLocation", New Object() {startDate, endDate, city, region, stateAbbr, countryAbbr, continent, categories}, callback, asyncState)
        End Function
        Public Function EndBrowseByLocation(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/BrowseServices"), System.Web.Services.Protocols.SoapParameterAttribute("activityID", ElementName:="ActivityID")> BrowseServices(ByVal activityID As Long) As System.Data.DataSet
            Dim results As Object() = Me.Invoke("BrowseServices", New Object() {activityID})
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function BeginBrowseServices(ByVal activityID As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("BrowseServices", New Object() {activityID}, callback, asyncState)
        End Function
        Public Function EndBrowseServices(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/BrowseByProximity"), System.Web.Services.Protocols.SoapParameterAttribute("startDate", ElementName:="StartDate"), System.Web.Services.Protocols.SoapParameterAttribute("endDate", ElementName:="EndDate"), System.Web.Services.Protocols.SoapParameterAttribute("locationID", ElementName:="LocationID"), System.Web.Services.Protocols.SoapParameterAttribute("distance", ElementName:="Distance"), System.Web.Services.Protocols.SoapParameterAttribute("category", ElementName:="Category")> BrowseByProximity(ByVal startDate As String, ByVal endDate As String, ByVal locationID As Long, ByVal distance As Long, ByVal category As String) As System.Data.DataSet
            Dim results As Object() = Me.Invoke("BrowseByProximity", New Object() {startDate, endDate, locationID, distance, category})
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function BeginBrowseByProximity(ByVal startDate As String, ByVal endDate As String, ByVal locationID As Long, ByVal distance As Long, ByVal category As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("BrowseByProximity", New Object() {startDate, endDate, locationID, distance, category}, callback, asyncState)
        End Function
        Public Function EndBrowseByProximity(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/RefreshCategories")> RefreshCategories() As System.Data.DataSet
            Dim results As Object() = Me.Invoke("RefreshCategories", New Object() {})
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function BeginRefreshCategories(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("RefreshCategories", New Object() {}, callback, asyncState)
        End Function
        Public Function EndRefreshCategories(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),System.Data.DataSet)
        End Function
        
    End Class
End Namespace
