'------------------------------------------------------------------------------
' <autogenerated>
'     This class was generated by a tool.
'     Runtime Version: 2000.14.1812.10
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Imports System.Xml.Serialization
Imports System.Web.Services.Protocols
Imports System.Web.Services

Namespace VistaSiteMgr
    Public Class AirlineServiceServiceService
        Inherits System.Web.Services.Protocols.SoapClientProtocol
        
        Public Sub New()
            MyBase.New
            Me.Path = "http://localhost/AirlineService/AirlineService.dll?Handler=Default"
        End Sub
        
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("#FindFlight", RequestNamespace:="urn:AirlineServiceService-service", ResponseElementName:="FindFlightResponse", ResponseNamespace:="urn:AirlineServiceService-service"), System.Web.Services.Protocols.SoapParameterAttribute("departCity", ElementName:="DepartCity"), System.Web.Services.Protocols.SoapParameterAttribute("destination", ElementName:="Destination"), System.Web.Services.Protocols.SoapParameterAttribute("airline", ElementName:="Airline"), System.Web.Services.Protocols.SoapReturnAttribute(ElementName:="return")> FindFlight(ByVal departCity As String, ByVal destination As String, ByVal airline As String) As String
            Dim results As Object() = Me.Invoke("FindFlight", New Object() {departCity, destination, airline})
            return CType(results(0),String)
        End Function
        Public Function BeginFindFlight(ByVal departCity As String, ByVal destination As String, ByVal airline As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("FindFlight", New Object() {departCity, destination, airline}, callback, asyncState)
        End Function
        Public Function EndFindFlight(ByVal asyncResult As System.IAsyncResult) As String
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),String)
        End Function
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("#BookFlight", RequestNamespace:="urn:AirlineServiceService-service", ResponseElementName:="BookFlightResponse", ResponseNamespace:="urn:AirlineServiceService-service"), System.Web.Services.Protocols.SoapParameterAttribute("flightID", ElementName:="FlightID"), System.Web.Services.Protocols.SoapParameterAttribute("customerName", ElementName:="CustomerName"), System.Web.Services.Protocols.SoapParameterAttribute("billingAddress", ElementName:="BillingAddress"), System.Web.Services.Protocols.SoapParameterAttribute("billingCity", ElementName:="BillingCity"), System.Web.Services.Protocols.SoapParameterAttribute("billingState", ElementName:="BillingState"), System.Web.Services.Protocols.SoapParameterAttribute("billingZip", ElementName:="BillingZip"), System.Web.Services.Protocols.SoapParameterAttribute("fFNumber", ElementName:="FFNumber"), System.Web.Services.Protocols.SoapParameterAttribute("cost", ElementName:="Cost"), System.Web.Services.Protocols.SoapParameterAttribute("seat", ElementName:="Seat"), System.Web.Services.Protocols.SoapReturnAttribute(ElementName:="return")> BookFlight(ByVal flightID As Integer, ByVal customerName As String, ByVal billingAddress As String, ByVal billingCity As String, ByVal billingState As String, ByVal billingZip As String, ByVal fFNumber As String, ByVal cost As Single, ByVal seat As String) As Integer
            Dim results As Object() = Me.Invoke("BookFlight", New Object() {flightID, customerName, billingAddress, billingCity, billingState, billingZip, fFNumber, cost, seat})
            return CType(results(0),Integer)
        End Function
        Public Function BeginBookFlight(ByVal flightID As Integer, ByVal customerName As String, ByVal billingAddress As String, ByVal billingCity As String, ByVal billingState As String, ByVal billingZip As String, ByVal fFNumber As String, ByVal cost As Single, ByVal seat As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("BookFlight", New Object() {flightID, customerName, billingAddress, billingCity, billingState, billingZip, fFNumber, cost, seat}, callback, asyncState)
        End Function
        Public Function EndBookFlight(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),Integer)
        End Function
        
    End Class
End Namespace
