'------------------------------------------------------------------------------
' <autogenerated>
'     This class was generated by a tool.
'     Runtime Version: 2000.14.1812.10
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Imports System.Xml.Serialization
Imports System.Web.Services.Protocols
Imports System.Web.Services

Namespace VistaSiteMgr
    Public Class Order
        Inherits System.Web.Services.Protocols.SoapClientProtocol
        
        Public Sub New()
            MyBase.New
            Me.Path = "http://localhost/POILib/Order.asmx"
        End Sub
        
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/Create")> Create() As System.Data.DataSet
            Dim results As Object() = Me.Invoke("Create", New Object() {})
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function BeginCreate(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("Create", New Object() {}, callback, asyncState)
        End Function
        Public Function EndCreate(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/load", RequestElementName:="load", ResponseElementName:="loadResult"), System.Web.Services.Protocols.SoapParameterAttribute("confirmationNumber", ElementName:="ConfirmationNumber")> Load(ByVal confirmationNumber As Long) As System.Data.DataSet
            Dim results As Object() = Me.Invoke("Load", New Object() {confirmationNumber})
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function BeginLoad(ByVal confirmationNumber As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("Load", New Object() {confirmationNumber}, callback, asyncState)
        End Function
        Public Function EndLoad(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),System.Data.DataSet)
        End Function
        Public Function <System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/Save"), System.Web.Services.Protocols.SoapParameterAttribute("orderInfo", ElementName:="OrderInfo")> Save(ByVal orderInfo As System.Data.DataSet) As Long
            Dim results As Object() = Me.Invoke("Save", New Object() {orderInfo})
            return CType(results(0),Long)
        End Function
        Public Function BeginSave(ByVal orderInfo As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            return Me.BeginInvoke("Save", New Object() {orderInfo}, callback, asyncState)
        End Function
        Public Function EndSave(ByVal asyncResult As System.IAsyncResult) As Long
            Dim results As Object() = Me.EndInvoke(asyncResult)
            return CType(results(0),Long)
        End Function
        
    End Class
End Namespace
